highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Emil Karlsson

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Emil Karlsson's Resume
name: Emil Karlsson
email: emilingemarkarlsson@gmail.com
email_full: mailto:emilingemarkarlsson@gmail.com
website: github.io/sustain
website_full: https://biomadeira.github.io/sustain
github: trending
twitter: twitter
tel: +46 7037 26965
tel_full: tel:+46703726965
google_maps: 'https://www.google.co.uk/maps/place/Pilgatan+10,+553+18+J%C3%B6nk%C3%B6ping,+Sverige/@57.7804095,14.1513893,17z/data=!3m1!4b1!4m5!3m4!1s0x465a6de8b5a6dcf1:0x7ff8c35fa543113d!8m2!3d57.7804095!4d14.1535833'
address: Pilgatan 10
postcode: 55 318
city: Jonkoping
country: Sweden
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
